### ISSUE TITLE
BitmapSource.Create（） 创建新图片时总报错

### ISSUE THREAD

**Issue by ronyuzhang** [mgenware/coldfunction#55]
总报异常 值不在预期内
var cut = new Int32Rect(faceBoxSource.Left, faceBoxSource.Top, faceBoxSource.Right - faceBoxSource.Left, faceBoxSource.Bottom - faceBoxSource.Top);
                            //Console.WriteLine("faceBoxSource.Left:" + faceBoxSource.Left);
                            //Console.WriteLine("faceBoxSource.Right:" + faceBoxSource.Right);
                            //计算Stride
                            var stride = this.colorBitmap.Format.BitsPerPixel * cut.Width / 8;
                            Console.WriteLine("stride:" + stride);
                            Console.WriteLine("cut.Height:" + cut.Height);
                            //声明字节数组
                            byte[] data = new byte[cut.Height * stride];

                            //调用CopyPixels
                            colorBitmap.CopyPixels(cut, data, stride, 0);
                            BitmapSource newBitmap = BitmapSource.Create(500, 400, 0 ,0, PixelFormats.Bgr32, null, data, stride);

**Comment by mgenware** [comment]
@ronyuzhang 给我个可以复现问题的工程？

**Comment by mgenware** [comment]
没有回应，暂时关掉，有问题，可以再打开。
